# -*- coding: utf-8 -*-
"""api_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STmwVV_yRY3mdZAqxyu16uxeOETY8HYU
"""

import pandas as pd
from supabase import create_client, Client
import requests
import urllib.parse
from sqlalchemy import create_engine

raw_password = "krishlad@542006"
safe_password = urllib.parse.quote(raw_password)

DATABASE_URL = f"postgresql://postgres.fnlpabicinbydknyprez:{safe_password}@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres"
engine = create_engine(DATABASE_URL,
                       connect_args={
                           "sslmode":"require",
                           "connect_timeout": 15})

print("Testing IPv4 Pooler Connection...")
try:
    with engine.connect() as conn:
        print("Success! Google Colab is now talking to Supabase via IPv4.")
except Exception as e:
    print("Connection failed. Error details:\n", e)

url = "https://api.openweathermap.org/data/2.5/forecast?lat=33.0&lon=-94&appid=667664b6c95a464e6d5733c23e09d42c&units=metric"
response = requests.get(url)
data = response.json()

df = pd.json_normalize(data['list'])

df['datetime'] = pd.to_datetime(df['dt_txt'])
df['date'] = df['datetime'].dt.date

df_cleaned = df.drop(['dt','wind.gust', 'sys.pod','main.sea_level', 'main.grnd_level','pop','dt_txt','main.feels_like','weather','main.temp_min','main.temp_max'], axis=1)

if 'rain.3h' in df_cleaned.columns:
    df_cleaned['rain.3h'] = df_cleaned['rain.3h'].fillna(0)
else:
    print("Column 'rain.3h' not found in the DataFrame.")

df_cleaned['visibility'] = df_cleaned['visibility'] / 1000.0

df_daily = df_cleaned.groupby('date').agg({
    'main.temp': 'mean',
    'main.humidity': 'mean',
    'wind.speed': 'mean',
    'main.pressure': 'mean',
    'wind.deg': 'mean',
    'clouds.all': 'mean',
    'visibility': 'mean',
    'rain.3h': 'sum'

}).reset_index()

df_daily.rename(columns={'rain.3h': 'precipitation'}, inplace=True)

df_daily['date'] = df_daily['date'].astype(str)

df_daily = df_daily.rename(columns = {"main.temp" : "temp", "main.humidity" : "humidity",
                                      "wind.speed" : "wind_speed", "main.pressure" : "pressure",
                                      "wind.deg" : "wind_deg", "clouds.all" : "clouds",
                                      })

try:
  existing_dates = pd.read_sql('SELECT date FROM api_data', engine)['date'].astype(str).tolist()
except Exception:
  existing_dates = []

df_new_dates = df_daily[~df_daily['date'].astype(str).isin(existing_dates)]

if not df_new_dates.empty:
  df_new_dates.to_sql('api_data', con= engine, if_exists='append', index = False)
  print("New dates found and added to the database.")
else:
  print("No new dates found.")